"""Add description to Worklog

Revision ID: 2b79fb4a888d
Revises: 
Create Date: 2025-08-29 21:16:05.588354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b79fb4a888d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_log', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
